### ISSUE TITLE
If number of hosts are more than required the playbook fails

### ISSUE THREAD

**Issue by poornimag** [gluster/gbench#44]
I had given 4 hosts, 3 clients, and volume configuration of type 1 * 3. I see the following failure(failed is set to 1 in 4th server node):

TASK [create-gluster-volume : Starts the created volume] ********************************************************************************************************************
changed: [shakthi1.lab.eng.blr.redhat.com -> shakthi1.lab.eng.blr.redhat.com]
	to retry, use: --limit @/home/poornima/workspace/sources/gbench/ansible-playbook-base/site.retry

PLAY RECAP ******************************************************************************************************************************************************************
benki1.lab.eng.blr.redhat.com : ok=11   changed=0    unreachable=0    failed=0   
benki2.lab.eng.blr.redhat.com : ok=11   changed=0    unreachable=0    failed=0   
benki4.lab.eng.blr.redhat.com : ok=11   changed=0    unreachable=0    failed=0   
localhost                  : ok=5    changed=5    unreachable=0    failed=0   
shakthi1.lab.eng.blr.redhat.com : ok=31   changed=12   unreachable=0    failed=0   
shakthi2.lab.eng.blr.redhat.com : ok=24   changed=7    unreachable=0    failed=0   
shakthi3.lab.eng.blr.redhat.com : ok=24   changed=7    unreachable=0    failed=0   
shakthi4.lab.eng.blr.redhat.com : ok=3    changed=0    unreachable=0    failed=1   

Is this expected?

The 4th host is not prepared, no gluster installed, disks formatted. I think, all the hosts specified should be setup, if we plan to use multiple volume configurations or expand the volume?

**Comment by ShyamsundarR** [comment]
As I try to reproduce this behavior, can you pass the various variable and inventory files along?

Specifically, inventory details and group details.

From the way the plays are structured, prepare-gluster-server, common and install-repos role should be run on all hosts in the servers group. Which means all servers above should have the packages and other such components installed and also be a part of the cluster.

One suspicion I have is that shakthi4 is not part of servers group in the inventory.

**Comment by ShyamsundarR** [comment]
@poornimag Provided a patch, as I was able to replicate the issue as detailed. Lmk if this works for you.
